# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'ui/start.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.4
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets


# Окно, которое открывается по кнопке "Let's Talk"
class Ui_Start(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(400, 640)
        Form.move(1287, 0)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(45, 45, 311, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Создание кнопки "Delete last sign"
        self.button_last_sign = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_last_sign.setEnabled(True)
        self.button_last_sign.setObjectName("button_last_sign")
        self.verticalLayout.addWidget(self.button_last_sign)

        # Создание кнопки "Duplicate last sign"
        self.button_duplicate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_duplicate.setObjectName("button_duplicate")
        self.verticalLayout.addWidget(self.button_duplicate)

        # Создание текстового окна - 'окна предсказаний', в котором будет выводиться переменная 'text'
        self.start_window = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.start_window.setReadOnly(True)
        self.start_window.setObjectName("start_window")
        self.verticalLayout.addWidget(self.start_window)
        self.start_window.setPlainText('')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # По нажатию кнопки "Delete last sign" (button_last_sign) будет производится удаление последнего записанного знака
        # из 'строки предсказаний' вверху экрана при условии работы модели в режиме 'model_stop'
        self.button_last_sign.clicked.connect(self.delete_last)

        # По нажатию кнопки "Duplicate last sign" (button_duplicate) будет производится дублирование последнего записанного знака
        # в 'строке предсказаний' вверху экрана при условии работы модели в режиме 'model_stop'
        self.button_duplicate.clicked.connect(self.duplicate_last)

    # удаление последнего знака
    @staticmethod
    def delete_last():
        from api.webcam_prediction import sentence, start_pause_predictions
        if len(start_pause_predictions) > 0 and start_pause_predictions[-1] == 'model_stop':
            try:
                sentence.pop()
            except:
                pass

    # дублирование последнего знака
    @staticmethod
    def duplicate_last():
        from api.webcam_prediction import sentence, start_pause_predictions
        if len(start_pause_predictions) > 0 and start_pause_predictions[-1] == 'model_stop':
            try:
                sentence.append(sentence[-1].lower())
            except:
                pass

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Let\'s talk"))
        self.button_last_sign.setText(_translate("Form", "Delete last sign"))
        self.button_duplicate.setText(_translate("Form", "Duplicate last sign"))
